version: "3.8"

services: 
  db-pe-na-trilha: 
    image: postgres
    ports:
      - "5432:5432"
    container_name: "db-pe-na-trilha"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pe_na_trilha
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data:
