version: "3.8"

services: 
  db-pe-na-trilha: 
    image: postgres
    ports:
      - "5432:5432"
    container_name: "db-pe-na-trilha"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes: 
  postgres: